name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby (for Bundler & SwiftLint)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies with Bundler
        run: |
          gem install bundler
          bundle install

      - name: Run SwiftLint
        run: bundle exec swiftlint --strict

      - name: Build app
        run: |
          xcodebuild clean build \
            -scheme LastFMMusic \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            | xcpretty

      - name: Run tests
        run: |
          xcodebuild test \
            -scheme LastFMMusic \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            | xcpretty
