name: iOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: LastFMMusic

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Run SwiftLint
        run: bundle exec swiftlint --strict

      - name: Run Tests
        run: |
          xcodebuild clean build test \
            -project LastFMMusic.xcodeproj \
            -scheme LastFMMusic \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 14" \
            CODE_SIGN_IDENTITY= \
            CODE_SIGNING_REQUIRED=NO
