name: iOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: LastFMMusic

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint --strict

      - name: Run Tests
        run: |
          xcodebuild clean build test \
            -project LastFMMusic.xcodeproj \
            -scheme LastFMMusic \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 14" \
            CODE_SIGN_IDENTITY= \
            CODE_SIGNING_REQUIRED=NO
